create table auction (id bigint not null auto_increment, current_price decimal(19,2), description varchar(255), end_date datetime(6), image_url varchar(255), name varchar(255), start_date datetime(6), start_price decimal(19,2), status integer, category_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table bid (id bigint not null auto_increment, bid_time datetime(6), price decimal(19,2), auction_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table category (id bigint not null auto_increment, category_description varchar(255), category_image_url varchar(255), category_name varchar(255), parent_id bigint, primary key (id)) engine=InnoDB;
create table news (id bigint not null auto_increment, content varchar(255), create_time datetime(6), image_url varchar(255), status integer, title varchar(255), update_time datetime(6), primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, address varchar(255), avatar varchar(255), city varchar(255), create_time datetime(6), email varchar(255), name varchar(255), password varchar(255), phone varchar(255), status integer, primary key (id)) engine=InnoDB;
alter table auction add constraint FKn177e55w3c2qy0osa460lcmgc foreign key (category_id) references category (id);
alter table auction add constraint FK2f5tf5bn1cn13dlhruo03ui5q foreign key (user_id) references user (id);
alter table bid add constraint FKhexc6i4j8i0tmpt8bdulp6g3g foreign key (auction_id) references auction (id);
alter table bid add constraint FK4abkntgv9nvsfi86p7kfl63au foreign key (user_id) references user (id);
create table auction (id bigint not null auto_increment, current_price decimal(19,2), description varchar(255), end_date datetime(6), image_url varchar(255), name varchar(255), start_date datetime(6), start_price decimal(19,2), status integer, category_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table bid (id bigint not null auto_increment, bid_time datetime(6), price decimal(19,2), auction_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table category (id bigint not null auto_increment, category_description varchar(255), category_image_url varchar(255), category_name varchar(255), parent_id bigint, primary key (id)) engine=InnoDB;
create table news (id bigint not null auto_increment, content varchar(255), create_time datetime(6), image_url varchar(255), status integer, title varchar(255), update_time datetime(6), primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, address varchar(255), avatar varchar(255), city varchar(255), create_time datetime(6), email varchar(255), name varchar(255), password varchar(255), phone varchar(255), status integer, primary key (id)) engine=InnoDB;
alter table auction add constraint FKn177e55w3c2qy0osa460lcmgc foreign key (category_id) references category (id);
alter table auction add constraint FK2f5tf5bn1cn13dlhruo03ui5q foreign key (user_id) references user (id);
alter table bid add constraint FKhexc6i4j8i0tmpt8bdulp6g3g foreign key (auction_id) references auction (id);
alter table bid add constraint FK4abkntgv9nvsfi86p7kfl63au foreign key (user_id) references user (id);
create table auction (id bigint not null auto_increment, current_price decimal(19,2), description varchar(255), end_date datetime(6), image_url varchar(255), name varchar(255), start_date datetime(6), start_price decimal(19,2), status integer, category_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table bid (id bigint not null auto_increment, bid_time datetime(6), price decimal(19,2), auction_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table category (id bigint not null auto_increment, category_description varchar(255), category_image_url varchar(255), category_name varchar(255), parent_id bigint, primary key (id)) engine=InnoDB;
create table news (id bigint not null auto_increment, content varchar(255), create_time datetime(6), image_url varchar(255), status integer, title varchar(255), update_time datetime(6), primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, address varchar(255), avatar varchar(255), city varchar(255), create_time datetime(6), email varchar(255), name varchar(255), password varchar(255), phone varchar(255), status integer, primary key (id)) engine=InnoDB;
alter table auction add constraint FKn177e55w3c2qy0osa460lcmgc foreign key (category_id) references category (id);
alter table auction add constraint FK2f5tf5bn1cn13dlhruo03ui5q foreign key (user_id) references user (id);
alter table bid add constraint FKhexc6i4j8i0tmpt8bdulp6g3g foreign key (auction_id) references auction (id);
alter table bid add constraint FK4abkntgv9nvsfi86p7kfl63au foreign key (user_id) references user (id);
create table auction (id bigint not null auto_increment, current_price decimal(19,2), description varchar(255), end_date datetime(6), image_url varchar(255), name varchar(255), start_date datetime(6), start_price decimal(19,2), status integer, category_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table bid (id bigint not null auto_increment, bid_time datetime(6), price decimal(19,2), auction_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table category (id bigint not null auto_increment, category_description varchar(255), category_image_url varchar(255), category_name varchar(255), parent_id bigint, primary key (id)) engine=InnoDB;
create table news (id bigint not null auto_increment, content varchar(255), create_time datetime(6), image_url varchar(255), status integer, title varchar(255), update_time datetime(6), primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, address varchar(255), avatar varchar(255), city varchar(255), create_time datetime(6), email varchar(255), name varchar(255), password varchar(255), phone varchar(255), status integer, primary key (id)) engine=InnoDB;
alter table auction add constraint FKn177e55w3c2qy0osa460lcmgc foreign key (category_id) references category (id);
alter table auction add constraint FK2f5tf5bn1cn13dlhruo03ui5q foreign key (user_id) references user (id);
alter table bid add constraint FKhexc6i4j8i0tmpt8bdulp6g3g foreign key (auction_id) references auction (id);
alter table bid add constraint FK4abkntgv9nvsfi86p7kfl63au foreign key (user_id) references user (id);
